config/routes.rb
Transapiio::Application.routes.draw do
  resources :templates

  get "home/index"

  get "home/dashboard"

  devise_for :users

  authenticated :user do
    root :to => 'home#dashboard'
  end

  root :to => 'home#index'

end

app/models/template.rb
class Template < ActiveRecord::Base

  attr_accessible :body, :from, :name, :subject, :template_type, :text_body, :user_id

  belongs_to :user

  validates :name,  presence: true,
                    format: /^[^ ]+$/
  validates :subject, presence: true
  validates :body, presence: true
  validates :from, presence: true
  validates :user_id, presence: true
  validates :template_type, presence: true
  validates :text_body, presence: true

  before_validation :replace_text_body

  def html_body
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, :autolink => true, :space_after_headers => true)
    markdown.render(self.body)
  end
  
  private
  def replace_text_body
  	if !self.text_body?
  		self.text_body = self.body
  	end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :name, :phone, :company_name, :remember_me
  # attr_accessible :title, :body

  #Validation
  validates :name, presence: true

  validates :phone, presence: true,
                    :phony_plausible => true

  validates :company_name, presence: true

  has_many :templates
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_filter :authenticate_user!, :except => [:index]
  
  def index
  end

  def dashboard
  end

  def home
  end
end

app/controllers/templates_controller.rb
class TemplatesController < ApplicationController
  before_filter :authenticate_user!
  # GET /templates
  # GET /templates.json
  def index
    #@templates = Template.all
    @templates = Template.where(:user_id => current_user.id).all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @templates }
    end
  end

  # GET /templates/1
  # GET /templates/1.json
  def show
    @template = Template.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @template }
    end
  end

  # GET /templates/new
  # GET /templates/new.json
  def new
    @template = Template.new
    @template.user_id = current_user.id
    @template_types = ['welcome','password reset','order confirmation']

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @template }
    end
  end

  # GET /templates/1/edit
  def edit
    @template = Template.find(params[:id])
    @template_types = ['welcome','password reset','order confirmation']
  end

  # POST /templates
  # POST /templates.json
  def create
    @template = Template.new(params[:template])

    respond_to do |format|
      if @template.save
        format.html { redirect_to @template, notice: 'Template was successfully created.' }
        format.json { render json: @template, status: :created, location: @template }
      else
        format.html { render action: "new" }
        format.json { render json: @template.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /templates/1
  # PUT /templates/1.json
  def update
    @template = Template.find(params[:id])

    respond_to do |format|
      if @template.update_attributes(params[:template])
        format.html { redirect_to @template, notice: 'Template was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @template.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /templates/1
  # DELETE /templates/1.json
  def destroy
    @template = Template.find(params[:id])
    @template.destroy

    respond_to do |format|
      format.html { redirect_to templates_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/templates_helper.rb
module TemplatesHelper
end

app/views/home/dashboard.html.erb
<h1>Home#dashboard</h1>
<p>Find me in app/views/home/dashboard.html.erb</p>

Secure

app/views/home/home.html.erb
<h1>Home</h1>
New Backend Home File

app/views/home/index.html.erb
<%= link_to 'Log In', new_user_session_path %>

app/views/layouts/_authenticate.html.erb
  <% if current_user %>
    Logged In as <%= current_user.name %> | <%= link_to 'Logout', destroy_user_session_path, :method => :delete %>
    <%= link_to 'Templates', templates_path %>
  <% else %>
    <%= link_to 'Log In', new_user_session_path %> | <%= link_to 'Sign Up', new_user_registration_path %>
  <% end %>

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Transapi.io</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.0.7/angular.min.js">
  </script>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body ng-app="transapiio">



   

app/views/layouts/_navigation.html.erb
  <div class='navbar navbar-inverse'>
    <div class='navbar-inner'>
      <div class='container-fluid'>
        <%= link_to '<i class="icon-truck"></i> Transapi.io'.html_safe, root_path, :class => 'brand' %>
      <% if current_user %>
        <ul class="nav ace-nav pull-right">
          <li class="grey">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="icon-tasks"></i>
              <span class="badge">4</span>
            </a>
            <ul class="pull-right dropdown-navbar dropdown-menu dropdown-caret dropdown-closer">
              <li class="nav-header">
                <i class="icon-ok"></i> 4 Tasks to complete
              </li>
              
              <li>
                <a href="#">
                  <div class="clearfix">
                    <span class="pull-left">Software Update</span>
                    <span class="pull-right">65%</span>
                  </div>
                  <div class="progress progress-mini"><div class="bar" style="width:65%"></div></div>
                </a>
              </li>
              
              <li>
                <a href="#">
                  <div class="clearfix">
                    <span class="pull-left">Hardware Upgrade</span>
                    <span class="pull-right">35%</span>
                  </div>
                  <div class="progress progress-mini progress-danger"><div class="bar" style="width:35%"></div></div>
                </a>
              </li>
              
              <li>
                <a href="#">
                  <div class="clearfix">
                    <span class="pull-left">Unit Testing</span>
                    <span class="pull-right">15%</span>
                  </div>
                  <div class="progress progress-mini progress-warning"><div class="bar" style="width:15%"></div></div>
                </a>
              </li>
              
              <li>
                <a href="#">
                  <div class="clearfix">
                    <span class="pull-left">Bug Fixes</span>
                    <span class="pull-right">90%</span>
                  </div>
                  <div class="progress progress-mini progress-success progress-striped active"><div class="bar" style="width:90%"></div></div>
                </a>
              </li>
              
              <li>
                <a href="#">
                  See tasks with details
                  <i class="icon-arrow-right"></i>
                </a>
              </li>
            </ul>
          </li>


          <li class="purple">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="icon-bell-alt icon-animated-bell icon-only"></i>
              <span class="badge badge-important">8</span>
            </a>
            <ul class="pull-right dropdown-navbar navbar-pink dropdown-menu dropdown-caret dropdown-closer">
              <li class="nav-header">
                <i class="icon-warning-sign"></i> 8 Notifications
              </li>
              
              <li>
                <a href="#">
                  <div class="clearfix">
                    <span class="pull-left"><i class="icon-comment btn btn-mini btn-pink"></i> New comments</span>
                    <span class="pull-right badge badge-info">+12</span>
                  </div>
                </a>
              </li>
              
              <li>
                <a href="#">
                  <i class="icon-user btn btn-mini btn-primary"></i> Bob just signed up as an editor ...
                </a>
              </li>
              
              <li>
                <a href="#">
                  <div class="clearfix">
                    <span class="pull-left"><i class="icon-shopping-cart btn btn-mini btn-success"></i> New orders</span>
                    <span class="pull-right badge badge-success">+8</span>
                  </div>
                </a>
              </li>
              
              <li>
                <a href="#">
                  <div class="clearfix">
                    <span class="pull-left"><i class="icon-twitter btn btn-mini btn-info"></i> Followers</span>
                    <span class="pull-right badge badge-info">+4</span>
                  </div>
                </a>
              </li>
                                
              <li>
                <a href="#">
                  See all notifications
                  <i class="icon-arrow-right"></i>
                </a>
              </li>
            </ul>
          </li>


          <li class="green">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="icon-envelope-alt icon-animated-vertical icon-only"></i>
              <span class="badge badge-success">5</span>
            </a>
            <ul class="pull-right dropdown-navbar dropdown-menu dropdown-caret dropdown-closer">
              <li class="nav-header">
                <i class="icon-envelope"></i> 5 Messages
              </li>
              
              <li>
                <a href="#">
                  <img alt="Alex's Avatar" class="msg-photo" src="assets/avatars/avatar.png" />
                  <span class="msg-body">
                    <span class="msg-title">
                      <span class="blue">Alex:</span>
                      Ciao sociis natoque penatibus et auctor ...
                    </span>
                    <span class="msg-time">
                      <i class="icon-time"></i> <span>a moment ago</span>
                    </span>
                  </span>
                </a>
              </li>
              
              <li>
                <a href="#">
                  <img alt="Susan's Avatar" class="msg-photo" src="assets/avatars/avatar3.png" />
                  <span class="msg-body">
                    <span class="msg-title">
                      <span class="blue">Susan:</span>
                      Vestibulum id ligula porta felis euismod ...
                    </span>
                    <span class="msg-time">
                      <i class="icon-time"></i> <span>20 minutes ago</span>
                    </span>
                  </span>
                </a>
              </li>
              
              <li>
                <a href="#">
                  <img alt="Bob's Avatar" class="msg-photo" src="assets/avatars/avatar4.png" />
                  <span class="msg-body">
                    <span class="msg-title">
                      <span class="blue">Bob:</span>
                      Nullam quis risus eget urna mollis ornare ...
                    </span>
                    <span class="msg-time">
                      <i class="icon-time"></i> <span>3:15 pm</span>
                    </span>
                  </span>
                </a>
              </li>
              
              <li>
                <a href="#">
                  See all messages
                  <i class="icon-arrow-right"></i>
                </a>
              </li>                 
  
            </ul>
          </li>


          <li class="light-blue user-profile">
            <a class="user-menu dropdown-toggle" href="#" data-toggle="dropdown">
              <img alt="<%=current_user.email.split("@")[0]%>'s Photo" src="assets/avatars/user.jpg" class="nav-user-photo" />
              <span id="user_info">
                <small>Welcome,</small> <%= current_user.email.split("@")[0] %>
              </span>
              <i class="icon-caret-down"></i>
            </a>
            <ul id="user_menu" class="pull-right dropdown-menu dropdown-yellow dropdown-caret dropdown-closer">
              <li><a href="#"><i class="icon-cog"></i> Settings</a></li>
              <li><a href="#"><i class="icon-user"></i> Profile</a></li>
              <li class="divider"></li>
              <li><%= link_to "Log Out", destroy_user_session_path, :method => :delete %></li>
            </ul>
          </li>
           



        </ul><!--/.ace-nav-->
      <%end%> 
      </div>
    </div>
  </div>

app/views/layouts/_sidebar.html.erb
    <div id="sidebar">
      <div class="">

        <div id="parcel">
          <ul class='nav nav-list'>
            <li><%= link_to 'Templates', templates_path %></li>        
          </ul>
        </div>

      </div>
    </div>

app/views/layouts/application.html.erb
<%= render 'layouts/header' %>

<%= render 'layouts/navigation' %>

  <div id="main-container" class="container-fluid">

    <% if current_user %>
    <div class="row-fluid">

      <div id="sidebar">
        <%= render "layouts/sidebar" %>
      </div><!--/#sidebar-->

    </div>
    <% end %>

    <div id="main-content" class="clearfix">
 
      <div class="row-fluid">
        <% if notice %>
        <p class="notice alert alert-warning"><%= notice %></p>
        <% end %>
        <% if alert %>
        <p class="alert alert-error"><%= alert %></p>
        <% end %>
      </div>


      <div id="page-content" class="clearfix">
        <%= yield %>
      </div>

    </div>

  </div>

</body>
</html>

app/views/templates/_form.html.erb
<div ng-controller="TemplateFormCtrl" ng-init="init(<%= @template.id %>)">
  <%= form_for(@template, :html => { :class => 'form-horizontal'}) do |f| %>
  <% if @template.errors.any? %>
    <div class="row" id="error_explanation">
      <h2><%= pluralize(@template.errors.count, "error") %> prohibited this template from being saved:</h2>

      <ul>
      <% @template.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :subject, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :subject %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :template_type, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :template_type, @template_types %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :body, :class => 'control-label' %>
    <div class="controls">
        <div id='wmd-button-bar'></div>
        <%= f.text_area :body, :class => 'wmd-input', :cols => '20', :rows => '15', 'ng-model' => 'template.body' %>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label">Preview</label>
    <div class="controls" id="markdown-preview">
      <div ng-bind-html-unsafe="template.body | markdown"></div>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label">HTML</label>
    <div class="controls" id="html-preview">
      <pre>{{template.body | markdown}}</pre>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :text_body, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :text_body, :class => 'autosize-transition', :rows => '15' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :from, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :from %>
    </div>
  </div>
  <%= f.hidden_field :user_id %>

  <div class="control-group">
    <div class="controls">
      <%= f.submit %>
    </div>
  </div>
<% end %>
</div>

app/views/templates/edit.html.erb
<h1>Editing template</h1>

<%= render 'form' %>

<%= link_to 'Show', @template %> |
<%= link_to 'Back', templates_path %>

app/views/templates/index.html.erb
<h1>Listing templates</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Subject</th>
      <th>Template type</th>
      <th>From</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>

  <% @templates.each do |template| %>
    <tr>
      <td><%= template.name %></td>
      <td><%= template.subject %></td>
      <td><%= template.template_type %></td>
      <td><%= template.from %></td>
      <td><%= template.user.name %></td>
      <td><%= link_to 'Show', template %></td>
      <td><%= link_to 'Edit', edit_template_path(template) %></td>
      <td><%= link_to 'Destroy', template, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Template', new_template_path %>

app/views/templates/new.html.erb
<h1>New template</h1>

<%= render 'form' %>

<%= link_to 'Back', templates_path %>

app/views/templates/show.html.erb
<p id="notice"><%= notice %></p>
<div ng-controller="TemplateFormCtrl" ng-init="init(<%= @template.id %>)">
<h2><%= @template.name %></h2>
<p>
  <strong>From:</strong> <%= @template.from %><br />
  <strong>Subject:</strong> <%= @template.subject %>
</p>
<hr />
<p>
  <div ng-bind-html-unsafe="template.body | markdown"></div>
</p>
</div>

<%= link_to 'Edit', edit_template_path(@template) %> |
<%= link_to 'Back', templates_path %>